/** Every shape `docs/research/lone-block-id` measured, as the note writes it. */
export const RESEARCH_SHAPES: Record<string, string> = {
  'paragraph, blank, id': 'Intro.\n\nSome prose.\n\n^p3\n\nOutro.\n',
  'table, blank, id': 'Intro.\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n\n^t1\n\nOutro.\n',
  'table, id directly under': 'Intro.\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n^t2\n\nOutro.\n',
  'quote, id directly under': 'Intro.\n\n> quoted\n^q2\n\nOutro.\n',
  'callout, blank, id': 'Intro.\n\n> [!note] Title\n> body\n\n^c1\n\nOutro.\n',
  'callout, id directly under': '> [!note] Title\n> body\n^c2\n\nAfter.\n',
  'fence, blank, id': 'Intro.\n\n```\ncode\n```\n\n^code1\n\nOutro.\n',
  'fence, id directly under': '```\ncode\n```\n^code2\n\nAfter.\n',
  'heading, blank, id': '## Head\n\n^h2\n\nbody\n',
  'heading, id directly under': '## Head\n^h3\n\nAfter.\n',
  'hr, blank, id': 'Before.\n\n***\n\n^hr1\n\nAfter.\n',
  'html, blank, id': '<div>html</div>\n\n^html1\n\nAfter.\n',
  'table, two blank lines, id': '| a | b |\n| --- | --- |\n| 1 | 2 |\n\n\n^t3\n\nAfter.\n',
  'paragraph, two blank lines, id': 'Prose.\n\n\n^p4\n\nAfter.\n',
  'table under a heading, blank, id': '## Head\n\n| x | y |\n| --- | --- |\n| 1 | 2 |\n\n^t6\n\nAfter.\n',
  'table, id with trailing spaces': '| a | b |\n| --- | --- |\n| 1 | 2 |\n\n^t4   \n\nAfter.\n',
  'table, blank, id, text directly under': '| a | b |\n| --- | --- |\n| 1 | 2 |\n\n^t5\nMore text.\n',
  'paragraph, blank, id, blank, id': 'Prose.\n\n^y1\n\n^y2\n\nAfter.\n',
  'id at the start of a note': '^first\n\nProse.\n',
  'indented id under an item': '- item a\n\n  ^under-a\n- item b\n',
  'indented id under the first of two loose items': '- a\n\n  ^x4\n\n- b\n',
  'indented id after an item and its child': '- a\n  - child\n\n  ^x1\n- b\n',
  'indented id after a nested item': '- a\n  - child\n\n    ^x2\n- b\n',
  'id after a paragraph inside an item': '- a\n\n  inner prose\n\n  ^x3\n- b\n',
  'table inside an item, blank, indented id': '- a\n\n  | x | y |\n  | --- | --- |\n  | 1 | 2 |\n\n  ^x5\n- b\n',
  'fence inside an item, blank, indented id': '- a\n\n  ```\n  code\n  ```\n\n  ^x6\n- b\n',
  'quote inside an item, indented id directly under': '- a\n\n  > quoted\n  ^x7\n- b\n',
  'id at column 0 directly under a list': '- a\n- b\n^l3\n\nAfter.\n',
  'list under a lead paragraph, id directly under': 'Lead.\n- a\n- b\n^l5\n\nAfter.\n',
  'list, blank, id': 'Before.\n\n- a\n- b\n\n^l1\n\nAfter.\n',
  'list under a lead paragraph, blank, id': 'Lead.\n- a\n- b\n  - nested c\n\n^l2\n\nAfter.\n',
  'list whose last item has a child, blank, id': '- a\n- b\n  - c\n\n^l4\n\nAfter.\n',
};
