import { describe, expect, it } from 'vitest';
import fc from 'fast-check';
import { encode } from '../src/encode';
import { parse } from '../src/parse';
import { treesEqual, walkNodes, type OutlineDoc, type OutlineNode } from '../src/model';
import { forestCoverOf } from '../src/escalate';
import { groupRootsByParent } from '../src/enforce';
import { nodeStartLine } from '../src/locate';
import {
  arbGroupOp,
  arbLabeledDoc,
  composeGroupOp,
  composeSequential,
  isReorder,
  labelOf,
  labelsOf,
  nodeByLabel,
  type GroupOpName,
} from './group-oracle';

function nodes(doc: OutlineDoc): OutlineNode[] {
  return [...walkNodes(doc)];
}

/** The cover between two nodes, as the operand the group ops take: its root
 * labels and how many parents those roots sit under. */
function operand(
  doc: OutlineDoc,
  i: number,
  j: number,
): { labels: string[]; groupCount: number } {
  const all = nodes(doc);
  const cover = forestCoverOf(doc, all[i % all.length]!, all[j % all.length]!);
  return {
    labels: cover.roots.map((root) => labelOf(root.node)!),
    groupCount: groupRootsByParent(cover.roots).length,
  };
}

/**
 * Whether the moved roots still form ONE cover holding exactly them — the
 * question the single-range after-state depends on. Stated over the project's
 * own forest geometry rather than line arithmetic, so a failure means "the
 * block-selection discriminator cannot express this", which is what matters.
 */
function movedRootsStayContiguous(result: OutlineDoc, labels: readonly string[]): boolean {
  const moved = labels.map((label) => nodeByLabel(result, label));
  if (moved.some((node) => node === undefined)) return false;
  const byLine = (moved as OutlineNode[])
    .map((node) => ({ node, line: nodeStartLine(result, node.id) }))
    .sort((a, b) => a.line - b.line);
  const after = forestCoverOf(result, byLine[0]!.node, byLine[byLine.length - 1]!.node);
  const afterLabels = after.roots.map((root) => labelOf(root.node));
  return (
    afterLabels.length === labels.length && labels.every((label) => afterLabels.includes(label))
  );
}

describe('group oracle support', () => {
  it('labels every node, uniquely, and round-trips', () => {
    fc.assert(
      fc.property(arbLabeledDoc(), (doc) => {
        const labels = labelsOf(doc);
        expect(labels).toHaveLength(nodes(doc).length);
        expect(new Set(labels).size).toBe(labels.length);
        // Ids are regenerated by `parse`, so compare structurally.
        expect(treesEqual(parse(encode(doc)), doc)).toBe(true);
      }),
      { numRuns: 300 },
    );
  });

  it('labels survive every operation under test', () => {
    fc.assert(
      fc.property(arbLabeledDoc(), fc.nat(), arbGroupOp, (doc, n, op) => {
        const all = nodes(doc);
        if (all.length === 0) return true;
        const target = labelOf(all[n % all.length]!)!;
        const composed = composeSequential(doc, [target], op);
        if (!composed.ok) return composed.reason !== 'label-lost';
        return (
          nodeByLabel(composed.doc, target) !== undefined &&
          new Set(labelsOf(composed.doc)).size === all.length
        );
      }),
      { numRuns: 1000 },
    );
  });
});

/**
 * Task 1.1/1.2 — the property the single-range after-state rests on, over the
 * operand the group operations actually accept (design D8).
 *
 * The first version of this asserted contiguity for every operation at every
 * cover shape, and measuring it is what produced D8: indent and outdent hold
 * anywhere, the reorders scatter their roots across scopes. It is kept in the
 * suite rather than deleted, so widening what the reorders accept fails HERE
 * instead of silently shipping a selection the editor cannot represent.
 */
describe('1.2 the moved subtrees stay contiguous over the accepted operand', () => {
  it('the forest cover of the moved roots holds exactly the moved roots', () => {
    fc.assert(
      fc.property(arbLabeledDoc(), fc.nat(), fc.nat(), arbGroupOp, (doc, i, j, op) => {
        if (nodes(doc).length === 0) return true;
        const { labels, groupCount } = operand(doc, i, j);
        const composed = composeGroupOp(doc, labels, op, groupCount);
        if (!composed.ok) return composed.reason !== 'label-lost';
        return movedRootsStayContiguous(composed.doc, labels);
      }),
      { numRuns: 4000 },
    );
  });

  it('indent and outdent are accepted at multi-parent cover shapes, not merely skipped', () => {
    // Guards the property above against passing vacuously: if the generator
    // stopped producing accepted multi-parent covers, the assertion would hold
    // while testing nothing.
    let accepted = 0;
    fc.assert(
      fc.property(arbLabeledDoc(), fc.nat(), fc.nat(), fc.constantFrom<GroupOpName>('indent', 'outdent'), (doc, i, j, op) => {
        if (nodes(doc).length === 0) return true;
        const { labels, groupCount } = operand(doc, i, j);
        if (groupCount < 2) return true;
        const composed = composeGroupOp(doc, labels, op, groupCount);
        if (composed.ok) accepted++;
        return true;
      }),
      { numRuns: 3000 },
    );
    expect(accepted).toBeGreaterThan(50);
  });
});

/**
 * Why the restriction exists, pinned as a property rather than left in prose.
 *
 * Without it, a multi-scope reorder moves each group within its OWN scope and
 * leaves the roots separated by content that was never selected. Measured at
 * 20 000 runs per operation: every accepted multi-parent move up tore (3100 of
 * 3100), and multi-parent move down was never accepted at all (0 of 8141).
 *
 * If this ever stops holding — someone gives the reorders a cross-scope
 * destination, say — this test failing is the signal to revisit D8, not a
 * regression to paper over.
 */
describe('1.2 the reorder restriction is load-bearing', () => {
  it('an unrestricted multi-parent reorder tears its roots apart whenever it is accepted', () => {
    let accepted = 0;
    fc.assert(
      fc.property(arbLabeledDoc(), fc.nat(), fc.nat(), arbGroupOp, (doc, i, j, op) => {
        if (!isReorder(op) || nodes(doc).length === 0) return true;
        const { labels, groupCount } = operand(doc, i, j);
        if (groupCount < 2) return true;
        // Deliberately the RAW composition: what the operation would do if the
        // restriction were lifted.
        const composed = composeSequential(doc, labels, op);
        if (!composed.ok) return true;
        accepted++;
        return !movedRootsStayContiguous(composed.doc, labels);
      }),
      { numRuns: 6000 },
    );
    expect(accepted).toBeGreaterThan(20);
  });
});
