#!/usr/bin/env node
// Claude Code hooks behind three conventions that instructions alone did not hold
// (docs/research/cloud-session-github-access.md):
//
// - Branches are named `feat/…`, `fix/…` or `chore/…`. A cloud session starts on a
//   `claude/<words>` branch the harness created, under a directive not to push
//   elsewhere without explicit permission. SessionStart grants it, in the session's
//   own context, and PreToolUse refuses a push or a PR that would put a `claude/*`
//   name on the remote — before the name is fixed by a PR, while a plain
//   `git branch -m` still fixes it.
// - A session arms no reminders or wakes for itself. The cloud environment's PR rules tell it
//   to keep a "safety-net" check-in through `send_later` (docs/research/pr-watching-wakes.md).
//   PreToolUse refuses `send_later` unless the maintainer asked for the reminder, and
//   `ScheduleWakeup` unless the maintainer typed `/loop`.
// - An agent never merges: the maintainer lands, by enabling auto-merge. AGENTS.md ("Change
//   lifecycle", step 5) says so, and PreToolUse refuses the direct forms as a guard behind it: the
//   GitHub MCP merge tools and the tools that enable or disable auto-merge, and in Bash `gh pr merge`, `gh stack merge` and a `gh api` write to a merge
//   route. It sees no more than that, and has no exception: it cannot tell a merge the maintainer
//   asked for from one the session chose.
// - PR descriptions carry no agent attribution. The GitHub MCP tool
//   `create_pull_request` appends a footer outside the `attribution` settings;
//   PostToolUse spots it and has the session rewrite the body, which sticks.
//
// One script, dispatched on the event, so `.claude/settings.json` names one file.
// Node rather than bash because the hook input is JSON and `jq` is not a given.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const HARNESS = /^(?:refs\/heads\/)?claude\//;
const TYPES = "`feat/<slug>`, `fix/<slug>` or `chore/<slug>`";
const SEND_LATER = "mcp__claude-code-remote__send_later";
const SCHEDULE_WAKEUP = "ScheduleWakeup";
// Disabling auto-merge is refused with enabling it: allowing one and not the other would need a rule
// about intent, and a session that finds a concern simply does not finish landing.
const MERGE_TOOLS = new Set([
  "mcp__github__merge_pull_request",
  "mcp__github__enable_pr_auto_merge",
  "mcp__github__disable_pr_auto_merge",
]);
// A pull request's `merge` route, its `auto-merge` route, or the cloud proxy's `…/ccr/auto_merge`, as
// a `repos/…` path. The number may be a shell variable and a query string may follow.
const MERGE_ROUTE = /(?:^|\/)repos\/[^/]+\/[^/]+\/pulls\/[^/?]+\/(?:merge|auto-merge|ccr\/auto_merge)(?:\?.*)?$/;
// A slash command the user typed is recorded in a `<command-name>` block of their message,
// slash included; a skill only the model can invoke is recorded without one.
const TYPED_LOOP = /<command-name>\/loop<\/command-name>/;
const FOOTER = /_?Generated by \[Claude Code\]\([^)]*\)_?\s*$/;

/** The fields of a Claude Code hook's input that this script reads. */
interface HookInput {
  cwd?: string;
  hook_event_name?: string;
  transcript_path?: string;
  tool_name?: string;
  tool_input?: Record<string, unknown>;
  tool_response?: unknown;
}

const input = JSON.parse(await readStdin()) as HookInput;
const cwd = input.cwd || process.cwd();

switch (input.hook_event_name) {
  case "SessionStart":
    sessionStart();
    break;
  case "PreToolUse":
    preToolUse();
    break;
  case "PostToolUse":
    postToolUse();
    break;
}

// Stdout becomes the session's context. The grant is what the harness directive
// asks for and CLAUDE.md alone never gave: a session reading "never push to a
// different branch without explicit permission" needs the permission in front of
// it, on the branch it applies to.
function sessionStart() {
  const branch = currentBranch();
  if (!branch || !HARNESS.test(branch)) return;
  console.log(
    [
      `agent-conventions: this session is on \`${branch}\`, a name the harness chose.`,
      `Our branches are named ${TYPES} (CLAUDE.md, "Branching and PR stacks"), and this`,
      "repository grants the permission the harness's branch directive asks for: before the",
      "first push, rename the branch to the change's type and slug — `git branch -m <type>/<slug>`",
      "— and push that name with `git push -u origin <type>/<slug>`. A push or a PR on a",
      "`claude/*` head is refused by a hook. Once a PR exists the name is fixed.",
    ].join("\n"),
  );
}

function preToolUse() {
  const { tool_name: tool, tool_input: args = {} } = input;
  if (tool === SEND_LATER) return refuseSelfReminder(args.initiation);
  if (tool === SCHEDULE_WAKEUP) return refuseSelfWake();
  if (tool && MERGE_TOOLS.has(tool)) return refuseMerge(`\`${tool}\``);
  let target: string | undefined;
  if (tool === "Bash") {
    const merge = mergeCommand(String(args.command ?? ""));
    if (merge) return refuseMerge(merge);
    target = pushedHarnessBranch(String(args.command ?? ""));
  } else if (tool === "mcp__github__create_pull_request") {
    const head = String(args.head ?? "");
    target = HARNESS.test(head) ? head : undefined;
  } else if (tool?.startsWith("mcp__github__")) {
    // push_files, create_branch, create_or_update_file, delete_file all name the
    // branch they write to the same way.
    const branch = String(args.branch ?? "");
    target = HARNESS.test(branch) ? branch : undefined;
  }
  if (!target) return;
  deny(
    `\`${target}\` is the name the harness chose for this session, and a push or a PR would fix it. ` +
      `Our branches are named ${TYPES}. Rename first — \`git branch -m <type>/<slug>\` — ` +
      "and push that name; this repository grants the permission the harness directive asks for.",
  );
}

// `initiation` says who wanted the reminder. Only `human_request` passes, so an absent value
// and any value the tool adds later are refused alike.
function refuseSelfReminder(initiation: unknown): void {
  if (initiation === "human_request") return;
  deny(
    `No self-armed check-ins (AGENTS.md, "PR events"; the \`steward\` skill): \`send_later\` with ` +
      `\`initiation: ${JSON.stringify(initiation ?? null)}\` is refused. Pushed GitHub events wake the session on ` +
      "their own, so skip the reminder and end the turn. `human_request` is for a reminder the " +
      "maintainer asked for in their own words.",
  );
}

// Landing is the maintainer's. A session prepares it, reports, and stops.
function refuseMerge(what: string): void {
  deny(
    `No merges by an agent (AGENTS.md, "Change lifecycle", step 5): ${what} is refused. Prepare landing ` +
      "and stop; the maintainer merges, or enables auto-merge, from the PR page. Report that the PR is ready and what, if " +
      "anything, is left.",
  );
}

// The merge a Bash command line makes, as the words to show in the refusal: the direct forms only,
// as a guard behind the instruction in AGENTS.md and no sandbox. The command word is any `gh` word
// among a simple command's words, so `env`, `xargs`, `sudo`, `time` and the like need no list of
// their options. `gh pr merge` and `gh stack merge` are named by their first two words that are not
// flags (`-R owner/repo` stands between them) and are refused with any flags; `gh api` is a merge
// when a word is a merge route and it writes, DELETE included: a session never turns auto-merge on or
// off, so a read of a route is all that passes.
//
// Not seen: `curl` and GraphQL mutations; a command inside `bash -c`, `eval`, backticks or `$(…)`;
// a variable or a script written first or piped to a shell; a `gh` alias; a function or a `case`
// arm that builds the command from its arguments; a subshell that opens the command
// (`(gh pr merge 1)`); and a `<<` the shell does not read as a here-document (arithmetic, a
// partly quoted delimiter) followed by a line equal to its word. Refused though it merges nothing:
// `gh pr merge --help`, an unquoted `echo gh pr merge`, `-X=GET` (which `gh` reads as GET), and a
// field whose value ends in a full merge-route URL.
function mergeCommand(command: string): string | undefined {
  for (const words of shellCommands(command)) {
    for (let i = 0; i < words.length; i++) {
      if (words[i]?.split("/").pop() !== "gh") continue;
      const found = ghMerge(words.slice(i + 1));
      if (found) return found;
    }
  }
}

// What `gh` was asked to do, past its flags: the `-R`/`--repo` value is not a word of the command.
function ghMerge(words: string[]): string | undefined {
  const positional: string[] = [];
  for (let i = 0; i < words.length; i++) {
    const word = words[i] ?? "";
    if (word === "-R" || word === "--repo") i++;
    else if (!word.startsWith("-")) positional.push(word);
  }
  const [group, subcommand] = positional;
  if ((group === "pr" || group === "stack") && subcommand === "merge") return `\`gh ${group} merge\``;
  if (group !== "api") return undefined;
  const route = words.find((w) => MERGE_ROUTE.test(w));
  if (route && apiWrites(words)) return `\`gh api\` to ${route}`;
}

// Whether a `gh api` call writes: an explicit method other than GET (the last of the method flags,
// as `gh` reads them), or none and a field or body, which `gh` sends as a POST.
function apiWrites(words: string[]): boolean {
  const flag = words.findLastIndex((w) => /^(-X|--method)(=|$)/.test(w) || /^-X./.test(w));
  if (flag >= 0) {
    const word = words[flag] ?? "";
    const method = /^--method=|^-X./.test(word) ? word.replace(/^--method=|^-X/, "") : (words[flag + 1] ?? "");
    return !/^GET$/i.test(method);
  }
  return words.some((w) => /^(-f|-F|--field|--raw-field|--input)(=|$)/.test(w) || /^-[fF]./.test(w));
}

// `ScheduleWakeup` has no `initiation`; it exists for a `/loop` the user started, so a wake
// is the maintainer's only when they typed `/loop` in this session.
function refuseSelfWake(): void {
  if (userTypedLoop(input.transcript_path)) return;
  deny(
    "No self-armed check-ins (AGENTS.md, \"PR events\"; the `steward` skill): `ScheduleWakeup` is " +
      "refused because the maintainer has not run `/loop` in this session. Pushed GitHub events wake " +
      "the session on their own, so skip the wake and end the turn.",
  );
}

// Only user messages count: the text `/loop` also sits in tool results and attachments.
// A transcript that cannot be read has no typed `/loop` in it.
function userTypedLoop(path: string | undefined): boolean {
  if (!path) return false;
  let text: string;
  try {
    text = readFileSync(path, "utf8");
  } catch {
    return false;
  }
  return text.split("\n").some((line) => {
    if (!TYPED_LOOP.test(line)) return false;
    try {
      const entry = JSON.parse(line) as { type?: string; message?: { content?: unknown } };
      const content = entry.message?.content;
      const typed = typeof content === "string" ? content : Array.isArray(content) ? content.filter(isText).map((b) => b.text).join("\n") : "";
      return entry.type === "user" && TYPED_LOOP.test(typed);
    } catch {
      return false;
    }
  });
}

function isText(block: unknown): block is { type: "text"; text: string } {
  const b = block as { type?: unknown; text?: unknown };
  return b?.type === "text" && typeof b.text === "string";
}

// The push targets of one command line, when any of them is a harness branch.
// Deletes are exempt: removing a `claude/*` branch is the convention, not a breach.
function pushedHarnessBranch(command: string): string | undefined {
  for (const words of shellCommands(command)) {
    while (words.length && /^[A-Za-z_]\w*=/.test(words[0] ?? "")) words.shift();
    if (words.shift() !== "git") continue;
    if (words[0] === "-C") words.splice(0, 2);
    if (words.shift() !== "push") continue;
    if (words.includes("--delete") || words.includes("-d")) continue;
    // `--all`, `--mirror` and a wildcard refspec publish every matching local
    // branch, a `claude/*` one included, whatever branch is checked out.
    if (words.includes("--all") || words.includes("--mirror") || words.some((w) => w.includes("*"))) {
      const local = localHarnessBranch();
      if (local) return local;
      continue;
    }
    const positional = words.filter((w) => !w.startsWith("-"));
    const refspecs = positional.slice(1);
    for (const spec of refspecs) {
      if (spec.startsWith(":")) continue;
      const [src = "", dst = src] = spec.split(":");
      if (HARNESS.test(dst)) return dst;
      if ((src === "HEAD" || src === "@") && dst === src) {
        const branch = currentBranch();
        if (branch && HARNESS.test(branch)) return branch;
      }
    }
    if (refspecs.length === 0) {
      const branch = currentBranch();
      if (branch && HARNESS.test(branch)) return branch;
    }
  }
}

// The simple commands of a shell line as word lists: quotes group words and
// hide operators, so a commit message is never read as a command of its own,
// and a here-document's body is skipped for the same reason. A newline ends a
// command. `$(…)` and backticks are not expanded; a push hidden in one is not caught.
function shellCommands(line: string): string[][] {
  const commands: string[][] = [[]];
  let word = "";
  let inWord = false;
  let quote: string | null = null;
  const heredocs: string[] = [];
  const endWord = () => {
    if (inWord) commands.at(-1)?.push(word);
    word = "";
    inWord = false;
  };
  const endCommand = () => {
    endWord();
    if (commands.at(-1)?.length) commands.push([]);
  };
  for (let i = 0; i < line.length; i++) {
    const c = line.charAt(i);
    if (quote) {
      if (c === quote) quote = null;
      else if (c === "\\" && quote === '"' && line.charAt(i + 1) === "\n") i++;
      else if (c === "\\" && quote === '"' && i + 1 < line.length) word += line.charAt(++i);
      else word += c;
    } else if (c === "'" || c === '"') {
      quote = c;
      inWord = true;
    } else if (c === "\\" && line.charAt(i + 1) === "\n") {
      i++; // a line continuation joins nothing and ends nothing
    } else if (c === "\\" && i + 1 < line.length) {
      word += line.charAt(++i);
      inWord = true;
    } else if (c === "#" && !inWord) {
      // A comment runs to the end of the line: an apostrophe or a trailing backslash in it opens
      // no quote and continues no line.
      while (i + 1 < line.length && line.charAt(i + 1) !== "\n") i++;
    } else if (c === "<" && line.startsWith("<<", i)) {
      // A here-document: its body is text, read from the next newline to the delimiter line.
      // A here-string's `<<<` matches no delimiter and is stepped over, so it opens no body.
      const delimiter = /^<<-?\s*(?:'([^']+)'|"([^"]+)"|\\?([^\s;|&<>()]+))/.exec(line.slice(i));
      endWord();
      if (delimiter) {
        heredocs.push(delimiter[1] ?? delimiter[2] ?? delimiter[3] ?? "");
        i += delimiter[0].length - 1;
      } else {
        i += 1;
      }
    } else if (c === "\n") {
      endCommand();
      for (const delimiter of heredocs.splice(0)) i = heredocEnd(line, i, delimiter) ?? i;
    } else if (/\s/.test(c)) {
      endWord();
    } else if (c === ";" || c === "|" || c === "&") {
      endCommand();
    } else {
      word += c;
      inWord = true;
    }
  }
  endWord();
  return commands.filter((c) => c.length);
}

// The index of the newline that ends a here-document's delimiter line, the newline at `newline`
// opening its body. Without such a line the text after it is not a body (`1<<2` in arithmetic opens
// none), and it is read as commands: the cautious side for a rule that refuses.
function heredocEnd(line: string, newline: number, delimiter: string): number | undefined {
  let start = newline + 1;
  while (start < line.length) {
    const next = line.indexOf("\n", start);
    const end = next === -1 ? line.length : next;
    const text = line.slice(start, end).replace(/^\t+/, "");
    start = end + 1;
    if (text === delimiter) return start - 1;
  }
}

// The MCP tool's footer is appended at creation, outside the session, and every
// REST write to the body through the cloud session's proxy appends it again — a
// clean body PATCHed with `gh api` comes back with the footer. The one path that
// stores a body as given is the MCP `update_pull_request`, which only the session
// can call; the hook reads the body and hands the rewrite to the session.
function postToolUse() {
  if (input.tool_name !== "mcp__github__create_pull_request") return;
  const { owner, repo } = input.tool_input ?? {};
  const number = /\/pull\/(\d+)|"number"\s*:\s*(\d+)/.exec(JSON.stringify(input.tool_response ?? ""));
  const pull = number?.[1] ?? number?.[2];
  if (!owner || !repo || !pull) return;
  const rewrite =
    "Rewrite its body without the footer using `update_pull_request` — the body as sent to " +
    "`create_pull_request`, and only through that tool: a REST `PATCH` gets the footer appended again " +
    '(CLAUDE.md, "Conventions").';
  let body: string;
  try {
    body = execFileSync("gh", ["api", `repos/${owner}/${repo}/pulls/${pull}`, "--jq", ".body"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
  } catch {
    return block(`PR #${pull} was created with the MCP tool, which appends a \`Generated by [Claude Code]\` footer. ${rewrite}`);
  }
  if (FOOTER.test(body)) {
    block(`PR #${pull} carries the harness's \`Generated by [Claude Code]\` footer. ${rewrite}`);
  }
}

function localHarnessBranch() {
  try {
    return execFileSync("git", ["for-each-ref", "--format=%(refname:short)", "refs/heads/claude/"], {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    })
      .split("\n")
      .find(Boolean);
  } catch {
    return undefined;
  }
}

function currentBranch() {
  try {
    return execFileSync("git", ["symbolic-ref", "--short", "-q", "HEAD"], {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return undefined;
  }
}

function deny(reason: string): void {
  console.log(
    JSON.stringify({
      hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason },
    }),
  );
}

function block(reason: string): void {
  console.log(JSON.stringify({ decision: "block", reason }));
}

function readStdin(): Promise<string> {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => resolve(data || "{}"));
  });
}
